#RAML 1.0 NamedExample
value:
 bookingId: b1
 bookingStartDate: 2023-01-01
 bookingEndDate: 2023-01-02
 amenitiesSelected: 
      - wifi
      - room service
 transportSelected:
     - town car service
     - airport shuttle
 food: vegetarian
 room: 
  roomID: rm1
    roomType: single rom 
    amount: 4000