#RAML 1.0 NamedExample
value:
 bookingId: b2
 bookingStartDate: 2023-01-01
 bookingEndDate: 2023-01-02
 amenitiesSelected: 
      - wifi
      - gym
      - dry cleaning
 transportSelected:
     - town car service
     - limousine service
 food: vegetarian
 room: 
  roomID: rm2
    roomType: single deluxe rom 
    amount: 4500