#%RAML 1.0 DataType
type: object
properties:
 bookingId: string
 bookingStartDate: date-only
 bookingEndDate: date-only
 amenitiesSelected: string[]
 transportSelected: string[]
 food: string
 room: !include  Room.raml