#%RAML 1.0 DataType
type: object
properties: 
    registrationId: string
    customerName: string
    title: string
    address: !include address.raml
    paymentType: string
examples:
   example1: !include 